server:
  port: 9101
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/local_demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456
    max-wait: 60000
    max-active: 100
    min-idle: 10
    initial-size: 10
